In [2]:

import numpy as np

In [3]:
#XOR function 
# X is input data matrix where each row is training example
X = np.array([[0,0], [0,1], [1,0], [1,1]])
# Y is output data matrix where each row is training example
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
#Sigmoid activation function 
def sig(z):
    return 1/(1 + np.exp(-z))

In [5]:
def derivativeSig(z):
    return sig(z)*(1 - sig(z))

In [6]:
# Random set of initial weights and bias
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
lr=.1 #Learning rate
weights,bias

(array([[ 0.9671113],
        [-0.9183824]]), array([-0.34937495]))

In [9]:
#Building neural network which does not have hidden layer
for iter in range(3000):
    output0=X
    #Doing forward propagation so get the predicted output value Yp 
    output=sig(np.dot(output0,weights)+bias)
    input_for_last_layer=np.dot(output0,weights)+bias
    #Output sum margin of error(first term)=Calculated - Target
    first_term=output-Y
    second_term=derivativeSig(input_for_last_layer) 
    first_two=first_term*second_term

    #Going through each of the feature using corresponding weights that should give the gradient
    #Multiplying W11 to feature1 and W12 to feature2 using vector multiplication
    #Derivative of sigmoid will give us gradient of activation funciton 
    changes+=np.dot(output0.T,first_two)
    #Update weights
    weights=weights-lr*changes
    bias_change=0.0
    #Update bias
    bias_change+=np.sum(first_two) 
    bias=bias-lr*bias_change 
#Final output    
output=sig(np.dot(X,weights)+bias)  
print(output)
weights,bias

[[  3.19897464e-04]
 [  6.40480830e-02]
 [  6.40483761e-02]
 [  9.36036087e-01]]


(array([[ 5.36526497],
        [ 5.36526008]]), array([-8.04719009]))